mystr = "Sunny is a good boy"
print(mystr[0:5])
print(mystr[11:15])
print(mystr[0:5:2])
print(mystr[-4:-2])
print(mystr[::])
print(mystr[::4896])
print(len(mystr))
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.capitalize())
print(mystr.lower())
print(mystr.count("o"))
print(mystr.find("s"))
print(mystr.upper())
print(mystr.endswith("boy"))
print(mystr.replace("is", "was"))
print(mystr[::-1])
